# Generated by Django 3.1.1 on 2020-09-08 14:18

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filestorage', '0002_remove_apifile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=1000, verbose_name='Полное название')),
                ('short_name', models.TextField(max_length=1000, verbose_name='Сокращенное название')),
                ('inn', models.CharField(max_length=50, validators=[core.validators.isdigit_validator], verbose_name='ИНН')),
                ('ogrn', models.CharField(max_length=50, validators=[core.validators.isdigit_validator], verbose_name='ОГРН')),
                ('revenue_2019', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Доход за 2019')),
                ('revenue_2018', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Доход за 2018')),
                ('revenue_growth', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Рост выручки')),
                ('revenue_growth_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Рост выручки в процентах')),
                ('purchases_wins', models.PositiveIntegerField(verbose_name='Удачных покупок')),
                ('purchases_total', models.PositiveIntegerField(verbose_name='Всего покупок')),
                ('purchases_lost', models.PositiveIntegerField(verbose_name='Покупок потеряно')),
                ('revenue_lost', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Потерянный доход')),
                ('bg_overpayment_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Перепата в процентах')),
                ('bg_sum', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Сумма')),
                ('competitor_inn', models.CharField(max_length=50, validators=[core.validators.isdigit_validator], verbose_name='ИНН Конкурента')),
                ('competitor_ogrn', models.CharField(max_length=50, validators=[core.validators.isdigit_validator], verbose_name='ОГРН Конкурента')),
                ('competitor_full_name', models.TextField(max_length=1000, verbose_name='Полное название конкурента')),
                ('competitor_short_name', models.TextField(max_length=1000, verbose_name='Сокращенное название конкурента')),
                ('competitor_growth_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Рост выручки конкурента в процентах')),
                ('competitor_purchases_wins', models.PositiveIntegerField(verbose_name='Удачных покупок конкурента')),
                ('competitor_purchases_total', models.PositiveIntegerField(verbose_name='Всего покупок конкурента')),
                ('competitor_bg_saving_economy', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Экономия кнкурента')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Коимпании',
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.TextField(max_length=1000, verbose_name='Имя')),
                ('phone', models.BigIntegerField(verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('purchase_number', models.CharField(max_length=50, validators=[core.validators.isdigit_validator], verbose_name='Реестровый номер торгов')),
                ('bg_type', models.CharField(max_length=100, verbose_name='Вид банковской гарантии')),
                ('bg_sum', models.PositiveIntegerField(verbose_name='Сумма гарнатии')),
                ('purchase_date', models.DateTimeField(verbose_name='Дата тендера(аукциона)')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала гарантии')),
                ('end_date', models.DateTimeField(verbose_name='Дата конца гарантии')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на гарантию',
                'verbose_name_plural': 'Заявки на гарантию',
            },
        ),
        migrations.CreateModel(
            name='CompanyRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_full_name', models.TextField(max_length=1000, verbose_name='Полное название конкурента')),
                ('competitor_short_name', models.TextField(max_length=1000, verbose_name='Сокращенное название конкурента')),
                ('competitor_growth_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Рост выручки конкурента в процентах')),
                ('account_number', models.CharField(max_length=16, validators=[core.validators.account_number_validator], verbose_name='Номер счета')),
                ('total', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Сумма')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('federal_law', models.CharField(max_length=20, verbose_name='ФЗ')),
                ('warranty_approved', models.BooleanField(default=False, verbose_name='Одобрена гарантия')),
                ('warranty_sum', models.PositiveIntegerField(verbose_name='Сумма гарнатии')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_recommends', to='core.company')),
            ],
            options={
                'verbose_name': 'Рекомендоация для компании',
                'verbose_name_plural': 'Рекомендоации для компании',
            },
        ),
        migrations.CreateModel(
            name='CompanyProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=250, verbose_name='Название банка')),
                ('account_number', models.CharField(max_length=16, validators=[core.validators.account_number_validator], verbose_name='Номер счета')),
                ('bik', models.CharField(max_length=50, validators=[core.validators.isdigit_validator], verbose_name='БИК')),
                ('dadata', models.JSONField(verbose_name='ДаДата')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_props', to='core.company')),
            ],
            options={
                'verbose_name': 'Реквизиы компании',
                'verbose_name_plural': 'Реквизиты компании',
            },
        ),
        migrations.CreateModel(
            name='CompanyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_files', to='core.company')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_files', to='filestorage.apifile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Файл компании',
                'verbose_name_plural': 'Файлы компании',
            },
        ),
    ]
