# Generated by Django 3.1.1 on 2020-09-10 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='bg_overpayment_percent',
            new_name='bg_overpayment_perc',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='full_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='short_name',
            new_name='company_short_name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='revenue_growth_percent',
            new_name='revenue_growth_perc',
        ),
        migrations.AddField(
            model_name='companyprop',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_props', to='auth.user'),
            preserve_default=False,
        ),
    ]
