# Generated by Django 3.1.1 on 2020-09-16 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200910_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании(лендинги)'},
        ),
        migrations.AlterModelOptions(
            name='companyprop',
            options={'verbose_name': 'Реквизиты компании', 'verbose_name_plural': 'Реквизиты компании'},
        ),
        migrations.AlterModelOptions(
            name='companyrecommend',
            options={'verbose_name': 'Рекомендация для компании', 'verbose_name_plural': 'Рекомендации для компании'},
        ),
        migrations.AlterField(
            model_name='company',
            name='competitor_bg_saving_economy',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Экономия конкурента'),
        ),
        migrations.AlterField(
            model_name='companyrecommend',
            name='warranty_sum',
            field=models.PositiveIntegerField(verbose_name='Сумма гарантии'),
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='companies', through='core.CompanyUser', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
