# Generated by Django 3.1.1 on 2020-09-17 09:31

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200916_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Компания: пользователь', 'verbose_name_plural': 'Компании: привязанные пользователи'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, validators=[core.validators.isdigit_validator], verbose_name='ИНН'),
        ),
    ]
