# Generated by Django 3.1.1 on 2020-09-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200921_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='law',
            field=models.CharField(default='', max_length=100, verbose_name='Закон'),
            preserve_default=False,
        ),
    ]
