# Generated by Django 3.1.1 on 2020-09-21 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_warranty_law'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='was_processed',
            field=models.BooleanField(default=False, verbose_name='Было обработано'),
        ),
        migrations.AlterField(
            model_name='companyrecommend',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_recommends', to='core.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='companyrecommend',
            name='competitor_full_name',
            field=models.TextField(max_length=1000, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='companyrecommend',
            name='competitor_short_name',
            field=models.TextField(max_length=1000, verbose_name='Предмет обращения'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='core.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано в'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
