# Generated by Django 3.1.1 on 2020-09-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200921_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyrecommend',
            old_name='competitor_full_name',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='companyrecommend',
            old_name='competitor_short_name',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='companyrecommend',
            name='competitor_growth_percent',
        ),
        migrations.AddField(
            model_name='companyrecommend',
            name='probability_of_victory',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Вероятность победы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyrecommend',
            name='tender_link',
            field=models.URLField(default='', verbose_name='Ссылка на тендер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyrecommend',
            name='account_number',
            field=models.CharField(max_length=250, verbose_name='Номер тендера'),
        ),
    ]
