# Generated by Django 3.1.1 on 2020-10-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200925_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='competitor_bg_saving_economy',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Экономия конкурента'),
        ),
        migrations.AlterField(
            model_name='companyrecommend',
            name='topic',
            field=models.TextField(max_length=1000, verbose_name='Описание закупки'),
        ),
    ]
