# Generated by Django 3.1.1 on 2020-10-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201001_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='competitor_bg_saving_economy',
            field=models.BigIntegerField(verbose_name='Экономия конкурента'),
        ),
    ]
