# Generated by Django 3.1.1 on 2020-10-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201001_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bg_overpayment_perc',
            field=models.CharField(max_length=250, verbose_name='Перепата в процентах'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bg_sum',
            field=models.CharField(max_length=250, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='company',
            name='competitor_growth_percent',
            field=models.CharField(max_length=250, verbose_name='Рост выручки конкурента в процентах'),
        ),
        migrations.AlterField(
            model_name='company',
            name='revenue_2018',
            field=models.CharField(max_length=250, verbose_name='Доход за 2018'),
        ),
        migrations.AlterField(
            model_name='company',
            name='revenue_2019',
            field=models.CharField(max_length=250, verbose_name='Доход за 2019'),
        ),
        migrations.AlterField(
            model_name='company',
            name='revenue_growth',
            field=models.CharField(max_length=250, verbose_name='Рост выручки'),
        ),
        migrations.AlterField(
            model_name='company',
            name='revenue_growth_perc',
            field=models.CharField(max_length=250, verbose_name='Рост выручки в процентах'),
        ),
        migrations.AlterField(
            model_name='company',
            name='revenue_lost',
            field=models.CharField(max_length=250, verbose_name='Потерянный доход'),
        ),
    ]
