# Generated by Django 3.1.1 on 2020-10-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201001_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='was_processed_manually',
            field=models.BooleanField(default=False, verbose_name='Документы проверены'),
        ),
    ]
