# Generated by Django 3.1.1 on 2020-10-12 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filestorage.utils
import filestorage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(blank=True, max_length=255, validators=[filestorage.validators.filename_validator], verbose_name='Имя файла')),
                ('ext', models.CharField(blank=True, max_length=255, verbose_name='Расширение файла')),
                ('file', models.FileField(upload_to=filestorage.utils.file_upload_to, verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('application', 'Приложение'), ('audio', 'Аудио'), ('video', 'Видео'), ('image', 'Изображение'), ('text', 'Текст'), ('other', 'Другое')], editable=False, max_length=255, verbose_name='Тип файла')),
                ('file_sub_type', models.CharField(blank=True, editable=False, max_length=255, verbose_name='Подтип файла')),
                ('file_duration', models.FloatField(blank=True, editable=False, null=True, verbose_name='Длительность файла (секунды)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-created_at'],
            },
        ),
    ]
