# Generated by Django 3.1.1 on 2020-09-20 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filestorage', '0002_remove_apifile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='apifile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='api_files', to='auth.user'),
            preserve_default=False,
        ),
    ]
